### PR TITLE
Audio only + ffmpeg

### PR DESCRIPTION
**Pull request by swiftyy-mage**
Audio only argument accepts a string input so you can specify which format you want, if none is provided it defaults to mp4. Changed ffmpeg support so now you can specify which resolution you wish to download. If you provide a resolution and an mp4 stream is available, it will pick that one. If no mp4 stream is available, it will pick the first stream with that resolution. If no resolution is provided, it will check the highest resolution stream against the highest resolution stream which is also an mp4. If these two streams have the same resolution, it will pick the mp4. If not, it will pick the highest quality stream available.
Once the correct video stream has been identified, it will find the correct audio stream. It then downloads both with a unique name, combines them using ffmpeg, and deletes the original adaptive streams.

I had some issues with pytest and unittest. I made two tests, one for the audio option an one for the ffmpeg option but they are very basic. @hbmartin I spent a little while trying to learn these modules (and will continue to learn about them), but any test I made to see if `download_audio` was processing things correctly failed. Any ideas?

### CODE REVIEW

**Comment by swiftyy-mage** [comment]
All the issues I can see are to do with subprocess, like "Starting a process with a partial executable path", or even just the fact that I have imported subprocess. Any ideas how to make those errors go away?

**Comment by hbmartin** [comment]
@swiftyy-mage Travis CI is showing that `black` is failing, so you need to run `black pytube` which will reformat files.
For the subprocess issues, try adding `  # nosec` on the flagged lines, which will disable the check. I'll merge regardless.

**Comment by swiftyy-mage** [comment]
Can we just leave that Travis check failing? Unless you know how to get it working. I literally have no idea how anyone is supposed to code with that machine staring over your shoulder the whole time.

**Comment by hbmartin** [comment]
Having seen enough screw ups, weird bugs, and hard to maintain code in 15 years of programming, I promise these checks are valuable 😺 If you're frustrated you can run `make test` in the repo directory and see locally what Travis will say.

Now, it's mypy failing not formatting: https://travis-ci.com/hbmartin/pytube3/jobs/282116807
`pytube/cli.py:325: error: Argument 2 to "unique_name" has incompatible type "Optional[str]"; expected "str"`

I think the problem here is that `stream.subtype` isn't guaranteed to *not* be `None`. You could remove it from `unique_name` since you already have `video_audio` or make it optional like `def unique_name(base: str, subtype: Optional[str], video_audio: str, target: str) -> str:` and check that it's not None in the function.

**Comment by hbmartin** [comment]
Feel free to hit me up in gmail chat or pyslackers slack in you want to talk in real time

**Comment by swiftyy-mage** [comment]
I'll get it done matey

**Comment by swiftyy-mage** [comment]
@hbmartin I'll make some more tests to increase coverage. Do you have any idea why `subtype` has to be optional? It's really been bugging me because the way I understand it, all `Stream` objects necessarily have the attribute `subtype` and it is always populated by `mime_type_codec` during initialization.

**Comment by hbmartin** [comment]
@swiftyy-mage thanks for making me dig into this. `Stream` was being initialized with a bunch of `None` properties that were then getting set from a dictionary. This is a no-no for several reasons which is why mypy was unhappy. I re-wrote `Stream` init in https://github.com/hbmartin/pytube3/pull/32
I'll take a closer look at your PR now and see how this helps here.

**Comment by swiftyy-mage** [comment]
@hbmartin Added a couple of tests. Not sure how much good they have done but I will have more soon. I emailed you btw.

**Comment by hbmartin** [comment]
@swiftyy-mage thanks for keeping at this 😄 As far as learning about testing goes, here's a quick breakdown and some link, happy to keep talking here or in email...
_Unit testing_  is testing method where the smallest individual pieces (usually meaning functions) of the program are tested. The idea is try to cover all of the scenarios that unit has to deal with so that we can rely on and reason about the behavior of the unit as a whole. It helps prevent bugs from being introduced in code when changes have an intended effect (which is common in poorly architected programs).
_Mocking_ is a way to isolate pieces of code from others by controlling what would hypothetically happen when the code we're testing relies on some other piece. Simple example would be a function that returns `"even"` or `"odd"` depending on the output of a random number generator - we'd want to mock the random number output in two different test cases.  Common example in our specific case is controlling what `request.get` returns. 
_Coverage_ is evaluating how many lines of the program are executed during all of the tests vs total number of lines in the program. This is the % number reported by codecov/coveralls. It help to find where the code might change (with unintended effects) without automatically reporting issues. I'm trying to keep us > 90% coverage here, the primary benefit to me is that we can optimize and refactor things with the confidence that we're not breaking other things.

This is an article written by a friend of mine that has some good examples of building of mocks from simple to more complex, (although the intro is too long lol) https://www.toptal.com/python/an-introduction-to-mocking-in-python
Real Python is always good, much the same material as above: https://realpython.com/python-mock-library/
And a decent broad summary: https://medium.com/@yeraydiazdiaz/what-the-mock-cheatsheet-mocking-in-python-6a71db997832

**Comment by swiftyy-mage** [comment]
Awesome. I'll give them a read, thanks.

**Pull request merged**
