### PR TITLE
Filter option for OTF videos that will 404

### PR DESCRIPTION
**Pull request by hbmartin**
* Adds `is_otf` property to `Stream`
* Filter like like `for s in yt.streams.otf().all(): ...` to avoid 404s
* Also, adds a `filesize_approx` stream property accurate to <0.1MB to avoid HTTP calls
* Refactors player config extraction (works better with age protected videos)
* Don't do unnecessary embed_html loading
* Ignore `sts` if unavailable when loading age protected videos
* Cleans up unnecessary functions in `extract`
* Adds flake8 linting plugins

### CODE REVIEW

**Comment by hbmartin** [comment]
@swiftyy-mage @movraxrsp I know y'all have looked into these issues before and I'm a bit nervous since taken together these are real changes to decrypting the streams. Can you take a look and try out with a few different videos?

**Comment by swiftyy-mage** [comment]
@hbmartin Will do.

**Comment by hbmartin** [comment]
@jslay can you try this branch and verify that it addresses https://github.com/hbmartin/pytube3/issues/47 ?
After that I can cut a release with these changes.

**Comment by hbmartin** [comment]
@jslay88 can you try this branch and verify that it addresses #47 ?
After that I can cut a release with these changes.

**Pull request merged**
