### PR TITLE
Resolution selection

### PR DESCRIPTION
**Pull request by hbmartin**
* Add `-r` flag to cli for getting video by resolution
* Refactor `resuests.get` into 3 separate function
* Adds `is_dash` property to streams
* Various cleanups in `playlist`
* Add `cache` annotation
* Add `get_by_resolution` and `get_lowest_resolution` to `query`
* More tests of course!

### CODE REVIEW

**Comment by swiftyy-mage** [comment]
I really like this, can't believe it wasn't a feature before.

**Comment by hbmartin** [comment]
@swiftyy-mage thanks! struggling a bit with progressive/dash and webm vs mp4... seems like most itags are webm here, but not sure if that's what people would expect when using this.

**Comment by hbmartin** [comment]
Let's continue progressive / webm discussion here: https://github.com/hbmartin/pytube3/issues/14

**Comment by swiftyy-mage** [comment]
Just tried downloading pytube3 on a venv but the changes on this PR aren't there. The fix I made earlier is, but I don't think any of the other stuff is.

**Comment by hbmartin** [comment]
These changes will be in the next release

**Pull request merged**
