### PR TITLE
do on_complete callback when file already exists

### PR DESCRIPTION
**Pull request by hbmartin**
@swiftyy-mage I'm not thrilled with this fix, but maybe good enough for this release
Alternatives I can think of:
* Throw an exception on dupes (seems extreme)
* Do something like your unique function and add a number (a little too magical, someone might be confused why it's happening)
* Add a bool to the complete callback indicating new/old (I like this as long as it doesn't break backward compatibility)

### CODE REVIEW

**Comment by swiftyy-mage** [comment]
I haven't actually tested this yet, but what if the user doesn't define their own on_complete function, then it would just do nothing right? It would be better just to print a simple message imo.

**Comment by RainbowAsteroids** [comment]
I was thinking of a new callback. If it's defined, then you run said callback. Otherwise, throw a [warning](https://docs.python.org/3/library/warnings.html).

**Comment by hbmartin** [comment]
@RainbowAsteroids what would be the usecase for a separate callback? I do like the idea of throwing a warning, but doesn't seem to fit with how those are typically used.

**Comment by RainbowAsteroids** [comment]
Nevermind what I said. The current way is fine now that I think about it. The goal was being able to control what happens when a file already exists and the programmer can do that via a simple `os.path.isfile()`.

**Pull request merged**
